using System.Threading.RateLimiting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpLogging;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.OpenApi.Models;
using PurrLobby.Services;
using PurrLobby.Models;


var builder = WebApplication.CreateBuilder(args);
builder.Services.AddProblemDetails();
builder.Services.AddHttpLogging(o =>
{
    o.LoggingFields = HttpLoggingFields.RequestScheme | HttpLoggingFields.RequestMethod | HttpLoggingFields.RequestPath | HttpLoggingFields.ResponseStatusCode;
});
builder.Services.AddResponseCompression(o =>
{
    o.Providers.Add<BrotliCompressionProvider>();
    o.Providers.Add<GzipCompressionProvider>();
});
builder.Services.AddRateLimiter(o =>
{
    o.GlobalLimiter = PartitionedRateLimiter.Create<HttpContext, string>(context =>
    {
        var key = context.Connection.RemoteIpAddress?.ToString() ?? "unknown";
        return RateLimitPartition.GetFixedWindowLimiter(key, _ => new FixedWindowRateLimiterOptions
        {
            PermitLimit = 300,
            Window = TimeSpan.FromMinutes(1),
            QueueProcessingOrder = QueueProcessingOrder.OldestFirst,
            QueueLimit = 100
        });
    });
    o.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
    o.OnRejected = async (context, ct) =>
    {
        context.HttpContext.Response.Headers.RetryAfter = "60";
        await context.HttpContext.Response.WriteAsync("Woah there partner calm down, you sending to much info :O", ct);
    };
});
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedHost;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(o =>
{
    o.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "PurrLobby API",
        Version = "v1",
        Description = "PurrLobby is a lightweight lobby service. Many endpoints require a 'gameId' cookie to scope requests to your game. Obtain it by calling POST /session/game.",
        Contact = new OpenApiContact { Name = "PurrLobby", Url = new Uri("https://purrlobby.exil.dev") }
    });

    o.AddSecurityDefinition("gameIdCookie", new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.ApiKey,
        In = ParameterLocation.Cookie,
        Name = "gameId",
        Description = "Game scope cookie set by POST /session/game."
    });

    o.AddSecurityDefinition("userIdCookie", new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.ApiKey,
        In = ParameterLocation.Cookie,
        Name = "userId",
        Description = "Player identity cookie generated by the server (POST /session/user)."
    });

    o.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "gameIdCookie" }
            },
            Array.Empty<string>()
        }
    });
});
builder.Services.AddSingleton<ILobbyEventHub, LobbyEventHub>();
builder.Services.AddSingleton<ILobbyService, LobbyService>();
builder.Services.AddRazorPages(); // Register Razor Pages services
var app = builder.Build();
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler();
    app.UseHsts();
}
else
{
    app.UseDeveloperExceptionPage();
}
app.UseHttpsRedirection();
app.UseForwardedHeaders();
app.UseResponseCompression();
app.UseHttpLogging();
app.UseRateLimiter();
app.UseWebSockets();
app.UseStaticFiles();
app.UseSwagger();
app.UseSwaggerUI();
app.MapRazorPages(); // Enable Razor Pages
static CookieOptions BuildStdCookieOptions() => new()
{
    HttpOnly = true,
    Secure = true,
    SameSite = SameSiteMode.Lax,
    IsEssential = true,
    Expires = DateTimeOffset.UtcNow.AddDays(7),
    Domain = "purrlobby.exil.dev"
};

// set / update gameId cookie
app.MapPost("/session/game", (HttpContext http, SetGameRequest req) =>
{
    var gameId = req.GameId;
    if (gameId == Guid.Empty)
        return Results.BadRequest("Invalid GameId");
    http.Response.Cookies.Append("gameId", gameId.ToString(), BuildStdCookieOptions());
    return Results.Ok(new { message = "GameId stored" });
})
.WithTags("Session")
.WithOpenApi(op =>
{
    op.Summary = "Identify game by setting a cookie";
    op.Description = "Sets a 'gameId' cookie used by lobby endpoints. Provide your game GUID in the request body.";
    op.Security.Clear();
    return op;
})
.Accepts<SetGameRequest>("application/json")
.Produces(StatusCodes.Status200OK)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// create / ensure userId cookie
app.MapPost("/session/user", (HttpContext http) =>
{
    if (!http.Request.Cookies.TryGetValue("userId", out var existing) || string.IsNullOrWhiteSpace(existing))
    {
        existing = Guid.NewGuid().ToString("N");
        http.Response.Cookies.Append("userId", existing, BuildStdCookieOptions());
    }
    return Results.Ok(new { userId = existing });
})
.WithTags("Session")
.WithOpenApi(op =>
{
    op.Summary = "Ensure a server-generated user id";
    op.Description = "Creates (if absent) and returns the server-generated 'userId' cookie used to identify the player. No input required.";
    op.Security.Clear();
    return op;
})
.Produces(StatusCodes.Status200OK);

// cookie helpers
static bool TryGetGameIdFromCookie(HttpRequest request, out Guid gameId)
{
    gameId = Guid.Empty;
    if (!request.Cookies.TryGetValue("gameId", out var v)) return false;
    return Guid.TryParse(v, out gameId);
}

static string EnsureUserIdCookie(HttpContext http)
{
    if (http.Request.Cookies.TryGetValue("userId", out var v) && !string.IsNullOrWhiteSpace(v))
        return v;
    var newId = Guid.NewGuid().ToString("N");
    http.Response.Cookies.Append("userId", newId, BuildStdCookieOptions());
    return newId;
}

// create lobby
app.MapPost("/lobbies", async (HttpContext http, ILobbyService service, CreateLobbyRequest req, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    if (req.MaxPlayers <= 0) return Results.BadRequest("MaxPlayers must be > 0");
    if (string.IsNullOrWhiteSpace(req.OwnerDisplayName)) return Results.BadRequest("OwnerDisplayName required");
    try
    {
        var ownerUserId = EnsureUserIdCookie(http);
        var lobby = await service.CreateLobbyAsync(gameId, ownerUserId, req.OwnerDisplayName, req.MaxPlayers, req.Properties, ct);
        return Results.Ok(lobby);
    }
    catch (ArgumentException ax)
    {
        return Results.BadRequest(ax.Message);
    }
})
.WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Create a lobby";
    op.Description = "Creates a new lobby for the current game. Owner user id is server generated (cookie 'userId').";
    return op;
})
.Accepts<CreateLobbyRequest>("application/json")
.Produces<Lobby>(StatusCodes.Status200OK)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// join lobby
app.MapPost("/lobbies/{lobbyId}/join", async (HttpContext http, ILobbyService service, string lobbyId, JoinLobbyRequest req, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    if (string.IsNullOrWhiteSpace(req.DisplayName)) return Results.BadRequest("DisplayName required");
    var userId = EnsureUserIdCookie(http);
    var lobby = await service.JoinLobbyAsync(gameId, lobbyId, userId, req.DisplayName, ct);
    return lobby is null ? Results.NotFound() : Results.Ok(lobby);
}).WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Join a lobby";
    op.Description = "Adds the current cookie user (server generated userId) to the specified lobby.";
    return op;
})
.Accepts<JoinLobbyRequest>("application/json")
.Produces<Lobby>(StatusCodes.Status200OK)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// leave lobby by id
app.MapPost("/lobbies/{lobbyId}/leave", async (HttpContext http, ILobbyService service, string lobbyId, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    var userId = EnsureUserIdCookie(http);
    var ok = await service.LeaveLobbyAsync(gameId, lobbyId, userId, ct);
    return ok ? Results.Ok() : Results.NotFound();
}).WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Leave a lobby";
    op.Description = "Removes the current cookie user from the lobby.";
    return op;
})
.Produces(StatusCodes.Status200OK)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// leave any lobby by user id
app.MapPost("/users/{userId}/leave", async (HttpContext http, ILobbyService service, string userId, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    var ok = await service.LeaveLobbyAsync(gameId, userId, ct);
    return ok ? Results.Ok() : Results.NotFound();
}).WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Force a user to leave their lobby";
    op.Description = "Removes the specified user from whichever lobby they are currently in for the current game.";
    return op;
})
.Produces(StatusCodes.Status200OK)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// search lobbies
app.MapGet("/lobbies/search", async (HttpContext http, ILobbyService service, int maxRoomsToFind = 10, CancellationToken ct = default) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    var lobbies = await service.SearchLobbiesAsync(gameId, maxRoomsToFind, null, ct);
    return Results.Ok(lobbies);
})
.WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Search available lobbies";
    op.Description = "Finds joinable lobbies for the current game. Excludes started or full lobbies.";
    op.Parameters.Add(new OpenApiParameter
    {
        Name = "maxRoomsToFind",
        In = ParameterLocation.Query,
        Required = false,
        Description = "Max rooms to return (default 10)",
        Schema = new OpenApiSchema { Type = "integer", Format = "int32" }
    });
    return op;
})
.Produces<List<Lobby>>(StatusCodes.Status200OK)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// get lobby by id
app.MapGet("/lobbies/{lobbyId}", async (HttpContext http, ILobbyService service, string lobbyId, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    var userId = EnsureUserIdCookie(http);
    var lobby = await service.GetLobbyAsync(gameId, lobbyId, userId, ct);
    return lobby is null ? Results.NotFound() : Results.Ok(lobby);
})
.WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Get lobby details";
    op.Description = "Returns the lobby object including ownership flag relative to current cookie user.";
    return op;
})
.Produces<Lobby>(StatusCodes.Status200OK)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest);

// lobby members
app.MapGet("/lobbies/{lobbyId}/members", async (HttpContext http, ILobbyService service, string lobbyId, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    var members = await service.GetLobbyMembersAsync(gameId, lobbyId, ct);
    return members.Count == 0 ? Results.NotFound() : Results.Ok(members);
})
.WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Get members of a lobby";
    op.Description = "Returns current members of the lobby in the current game, including readiness state.";
    return op;
})
.Produces<List<LobbyUser>>(StatusCodes.Status200OK)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// lobby data get
app.MapGet("/lobbies/{lobbyId}/data/{key}", async (HttpContext http, ILobbyService service, string lobbyId, string key, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    var v = await service.GetLobbyDataAsync(gameId, lobbyId, key, ct);
    return v is null ? Results.NotFound() : Results.Ok(v);
})
.WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Get a lobby data value";
    op.Description = "Retrieves a single property value for the lobby within the current game.";
    return op;
})
.Produces<string>(StatusCodes.Status200OK)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// lobby data set
app.MapPost("/lobbies/{lobbyId}/data", async (HttpContext http, ILobbyService service, string lobbyId, LobbyDataRequest req, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    if (string.IsNullOrWhiteSpace(req.Key)) return Results.BadRequest("Key is required");
    var ok = await service.SetLobbyDataAsync(gameId, lobbyId, req.Key, req.Value, ct);
    return ok ? Results.Ok() : Results.NotFound();
})
.WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Set a lobby data value";
    op.Description = "Sets or updates a single property on the lobby within the current game. Broadcasts a lobby_data event to subscribers.";
    return op;
})
.Accepts<LobbyDataRequest>("application/json")
.Produces(StatusCodes.Status200OK)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// ready toggle
app.MapPost("/lobbies/{lobbyId}/ready", async (HttpContext http, ILobbyService service, string lobbyId, ReadyRequest req, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    if (string.IsNullOrWhiteSpace(req.UserId)) return Results.BadRequest("UserId required");
    var ok = await service.SetIsReadyAsync(gameId, lobbyId, req.UserId, req.IsReady, ct);
    return ok ? Results.Ok() : Results.NotFound();
})
.WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Set member ready state";
    op.Description = "Sets readiness for the specified user in the lobby. Request body must include userId and isReady. Broadcasts a member_ready event.";
    return op;
})
.Accepts<ReadyRequest>("application/json")
.Produces(StatusCodes.Status200OK)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest)
.ProducesProblem(StatusCodes.Status400BadRequest);

// set all ready
app.MapPost("/lobbies/{lobbyId}/ready/all", async (HttpContext http, ILobbyService service, string lobbyId, AllReadyRequest req, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    if (string.IsNullOrWhiteSpace(req.UserId)) return Results.BadRequest("UserId required");
    var lobby = await service.GetLobbyAsync(gameId, lobbyId, req.UserId, ct);
    if (lobby is null) return Results.NotFound();
    if (!lobby.IsOwner) return Results.StatusCode(StatusCodes.Status403Forbidden);
    var ok = await service.SetAllReadyAsync(gameId, lobbyId, ct);
    return ok ? Results.Ok() : Results.BadRequest();
})
.WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Mark all members ready";
    op.Description = "Owner only. Sets all members' ready state to true and broadcasts all_ready. Requires userId in body identifying the acting owner.";
    return op;
})
.Accepts<AllReadyRequest>("application/json")
.Produces(StatusCodes.Status200OK)
.Produces(StatusCodes.Status403Forbidden)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest);

// start lobby
app.MapPost("/lobbies/{lobbyId}/start", async (HttpContext http, ILobbyService service, string lobbyId, CancellationToken ct) =>
{
    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");
    var userId = EnsureUserIdCookie(http);
    var lobby = await service.GetLobbyAsync(gameId, lobbyId, userId, ct);
    if (lobby is null) return Results.NotFound();
    if (!lobby.IsOwner) return Results.StatusCode(StatusCodes.Status403Forbidden);
    var ok = await service.SetLobbyStartedAsync(gameId, lobbyId, ct);
    return ok ? Results.Ok() : Results.BadRequest();
})
.WithTags("Lobbies")
.WithOpenApi(op =>
{
    op.Summary = "Start lobby";
    op.Description = "Owner only. Marks lobby as started and broadcasts lobby_started.";
    return op;
})
.Produces(StatusCodes.Status200OK)
.Produces(StatusCodes.Status403Forbidden)
.Produces(StatusCodes.Status404NotFound)
.Produces(StatusCodes.Status400BadRequest);

// lobby websocket
app.Map("/ws/lobbies/{lobbyId}", async (HttpContext http, string lobbyId, ILobbyEventHub hub, CancellationToken ct) =>
{
    if (!http.WebSockets.IsWebSocketRequest)
        return Results.BadRequest("Expected WebSocket");

    if (!TryGetGameIdFromCookie(http.Request, out var gameId))
        return Results.BadRequest("Missing or invalid gameId cookie");

    var userId = EnsureUserIdCookie(http);

    using var socket = await http.WebSockets.AcceptWebSocketAsync();
    await hub.HandleConnectionAsync(gameId, lobbyId, userId, socket, ct);
    return Results.Empty;
}).WithTags("Lobbies").WithOpenApi(op =>
{
    op.Summary = "Lobby Websocket";
    op.Description = "WebSocket for lobby-specific updates. Uses server-generated 'userId' cookie.";
    return op;
});

// health
app.MapGet("/health", () => Results.Ok(new { status = "healthy" }))
   .WithTags("Health")
   .WithOpenApi(op =>
   {
       op.Summary = "Service health";
       op.Description = "Returns a 200 response to indicate the service is running.";
       op.Security.Clear();
       return op;
   })
   .Produces(StatusCodes.Status200OK);

// stats
app.MapGet("/stats/global/players", async (ILobbyService service, CancellationToken ct) => Results.Ok(await service.GetGlobalPlayerCountAsync(ct)))
    .WithTags("Stats").WithSummary("Get total active players globally").WithDescription("Counts all players across all lobbies (all games).")
    .WithOpenApi(op => { op.Security.Clear(); return op; })
    .Produces<int>(StatusCodes.Status200OK);
app.MapGet("/stats/global/lobbies", async (ILobbyService service, CancellationToken ct) => Results.Ok(await service.GetGlobalLobbyCountAsync(ct)))
    .WithTags("Stats").WithSummary("Get total lobbies globally").WithDescription("Counts all lobbies across all games, including started ones.")
    .WithOpenApi(op => { op.Security.Clear(); return op; })
    .Produces<int>(StatusCodes.Status200OK);
app.MapGet("/stats/{gameId:guid}/lobbies", async (ILobbyService service, Guid gameId, CancellationToken ct) => Results.Ok(await service.GetLobbyCountByGameAsync(gameId, ct)))
    .WithTags("Stats").WithSummary("Get lobby count for a game").WithDescription("Counts all lobbies for the specified game.")
    .WithOpenApi()
    .Produces<int>(StatusCodes.Status200OK);
app.MapGet("/stats/{gameId:guid}/players", async (ILobbyService service, Guid gameId, CancellationToken ct) => Results.Ok(await service.GetActivePlayersByGameAsync(gameId, ct)))
    .WithTags("Stats").WithSummary("Get active players for a game").WithDescription("Returns distinct active players across all lobbies for the specified game.")
    .WithOpenApi()
    .Produces<List<LobbyUser>>(StatusCodes.Status200OK);

// run
app.Run();

// dto records
public record SetGameRequest(Guid GameId);
public record CreateLobbyRequest(string OwnerDisplayName, int MaxPlayers, Dictionary<string, string>? Properties);
public record JoinLobbyRequest(string DisplayName);
public record ReadyRequest(string UserId, bool IsReady);
public record AllReadyRequest(string UserId);
public record LobbyDataRequest(string Key, string Value);